version: "3"
services:
  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  order-service:
    image: akarklins/order:latest

  order-db:
    image: cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=order-cluster

  stock-service:
    image: akarklins/stock:latest

  stock-db:
    image: cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=stock-cluster

  payment-service:
    image: akarklins/user:latest

  payment-db:
    image: cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=payment-cluster
