version: "3"
services:
  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  order-service:
    build: ./order
    image: order:latest

  order-db:
    image: cassandra:latest

#  stock-service:
#    build: ./stock
#    image: stock:latest
#    env_file:
#      - env/stock_redis.env

#  stock-db:
#    image: redis:latest
#    command: redis-server --requirepass redis --maxmemory 512mb

#  payment-service:
#    build: ./payment
#    image: user:latest
#    env_file:
#      - env/payment_redis.env

#  payment-db:
#    image: redis:latest
#    command: redis-server --requirepass redis --maxmemory 512mb
