apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-db
spec:
  selector:
    matchLabels:
      app: stock-db
  template:
    metadata:
      labels:
        app: stock-db
    spec:
      containers:
        - name: stock-db
          image: cassandra:latest
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: "stock-cluster"
            - name: MAX_HEAP_SIZE
              value: "1G"
            - name: HEAP_NEWSIZE
              value: "256M"
          readinessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: stock-db
spec:
  selector:
    app: stock-db
  ports:
    - port: 9042
      targetPort: 9042
  type: ClusterIP